[program:clean-temp]
command = /opt/glpi/scheduler.sh --daily 04:00 --name "Clean Temp Files" -- php /var/www/glpi/bin/console glpi:system:clear-cache
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
