[program:inventory]
command = /opt/glpi/scheduler.sh --interval 600 --name "Inventory" -- php /var/www/glpi/bin/console glpi:inventory:import
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
