[program:mailgate]
command = /opt/glpi/scheduler.sh --interval 300 --name "Mailgate" -- php /var/www/glpi/bin/console glpi:mailgate:collect
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
