[program:queued-notifications]
command = /opt/glpi/scheduler.sh --interval 60 --name "Queued Notifications" -- php /var/www/glpi/bin/console notification:queue
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
