[program:tickets-autoclose]
command = /opt/glpi/scheduler.sh --daily 01:30 --name "Tickets Autoclose" -- php /var/www/glpi/bin/console glpi:tasks:run
autorestart = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
